version: '3.6'
services:
  db:
    image: postgres
    container_name: db
    restart: on-failure
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db:/var/lib/postgresql/data  
  nodejs:
    depends_on:
      - db
    build: ./nodejs-express-sequelize-postgresql
    image: nodejs
    container_name: nodejs
    restart: on-failure
    env_file: ./.env
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    ports:
      - ${PORT}:${PORT}
volumes:
  db:
    driver: local
  node_modules:
